# Content Creation & Testing Agent Prompt Template

system_prompt: |
  You are the Content Creation & Testing Agent for {{company_name}}, an advanced AI system specializing in generating high-quality marketing content and optimizing it through rigorous testing.

  Your primary responsibilities include:
  1. Creating multiple variations of content for different {{project_types}} (Email, Landing Page, Social Post, Blog)
  2. Ensuring all content strictly adheres to {{company_name}}'s {{brand_guidelines}}
  3. Generating content focused on specified {{content_topic}} areas
  4. Creating content optimized for key performance metrics including engagement, conversion, and SEO
  5. Designing A/B testing approaches to identify the highest-performing content variations

  You have access to the following resources:
  - Comprehensive brand guidelines including tone of voice, messaging frameworks, and terminology
  - Detailed content briefs from the Content Strategy Agent
  - Historical performance data on similar content
  - Target audience profiles and personas
  - SEO requirements and keyword targets

  Your content should be compelling, on-brand, strategically sound, and designed to achieve specific marketing objectives.

blog_post_template: |
  Create a high-quality blog post for {{company_name}} on the topic of {{content_topic}}. Generate 3 distinct variations with different approaches to the topic.

  ## Content Brief
  - Primary Topic: {{content_topic}}
  - Target Audience: {{target_audience}}
  - Primary Keyword: {{primary_keyword}}
  - Secondary Keywords: {{secondary_keywords}}
  - Target Word Count: {{word_count}}
  - Call to Action: {{call_to_action}}
  - Key Messages: {{key_messages}}

  ## Brand Guidelines
  {{brand_guidelines}}

  ## Content Requirements
  1. Create a compelling, attention-grabbing headline for each variation
  2. Include an engaging introduction that highlights the value to the reader
  3. Structure the content with clear headings and subheadings for readability
  4. Include relevant statistics, examples, or case studies to support key points
  5. Optimize for SEO using the primary and secondary keywords naturally
  6. Conclude with a strong call-to-action aligned with {{company_name}}'s objectives
  7. Ensure all content strictly adheres to the brand voice, tone, and messaging guidelines

  ## Output Format
  For each of the 3 variations, provide:
  1. Headline
  2. Meta description (150-160 characters)
  3. Full blog post content with proper formatting
  4. Rationale for the approach taken in this variation
  5. Expected strengths and performance characteristics of this variation

social_media_template: |
  Create a set of social media posts for {{company_name}} focused on {{content_topic}} for distribution across multiple platforms. Generate 3 variations for each platform.

  ## Content Brief
  - Primary Topic: {{content_topic}}
  - Target Audience: {{target_audience}}
  - Campaign Objective: {{campaign_objective}}
  - Key Messages: {{key_messages}}
  - Hashtags to Include: {{hashtags}}
  - Call to Action: {{call_to_action}}

  ## Platform Requirements
  - LinkedIn: Professional tone, industry insights, thought leadership (1200-1500 characters)
  - Twitter: Concise, engaging, question or statistic-driven (240 characters max)
  - Facebook: Conversational, visual-focused, community-building (100-250 words)
  - Instagram: Visual-first approach with supporting copy (caption up to 100 words)

  ## Brand Guidelines
  {{brand_guidelines}}

  ## Output Format
  For each platform, provide 3 variations including:
  1. Post copy
  2. Suggested image/visual description
  3. Hashtags (where appropriate)
  4. Call-to-action
  5. Rationale for the approach in this variation
  6. Expected engagement characteristics of this variation

email_template: |
  Create a marketing email for {{company_name}} focused on {{content_topic}}. Generate 3 distinct variations with different approaches.

  ## Content Brief
  - Email Purpose: {{email_purpose}}
  - Target Audience: {{target_audience}}
  - Key Benefit to Highlight: {{key_benefit}}
  - Call to Action: {{call_to_action}}
  - Required Elements: {{required_elements}}

  ## Brand Guidelines
  {{brand_guidelines}}

  ## Content Requirements
  1. Create compelling subject lines for each variation (max 50 characters)
  2. Include a pre-header text that complements the subject line (max 100 characters)
  3. Write engaging email body copy with clear value proposition
  4. Incorporate appropriate personalization elements
  5. Design a clear and compelling call-to-action
  6. Ensure all content strictly adheres to brand voice, tone, and messaging guidelines

  ## Output Format
  For each of the 3 variations, provide:
  1. Subject line
  2. Pre-header text
  3. Email body copy with proper sections and formatting
  4. Call-to-action button text and placement recommendation
  5. Rationale for the approach taken in this variation
  6. Expected performance characteristics (open rate, click-through)

landing_page_template: |
  Create landing page copy for {{company_name}} focused on {{content_topic}}. Generate 3 distinct variations with different approaches.

  ## Content Brief
  - Landing Page Purpose: {{landing_page_purpose}}
  - Target Audience: {{target_audience}}
  - Unique Value Proposition: {{value_proposition}}
  - Key Benefits to Highlight: {{key_benefits}}
  - Primary Call to Action: {{primary_cta}}
  - Secondary Call to Action: {{secondary_cta}}
  - Required Elements: {{required_elements}}

  ## Brand Guidelines
  {{brand_guidelines}}

  ## Content Requirements
  1. Create a compelling headline for each variation
  2. Write an engaging subheadline that supports the main headline
  3. Develop clear benefit statements that address audience pain points
  4. Include persuasive feature descriptions with benefit-focused language
  5. Add social proof elements (testimonial suggestions, trust indicators)
  6. Design primary and secondary CTAs with compelling action language
  7. Include FAQ section addressing common objections
  8. Ensure all content strictly adheres to brand voice, tone, and messaging guidelines

  ## Output Format
  For each of the 3 variations, provide:
  1. Headline
  2. Subheadline
  3. Complete landing page copy with proper sections and formatting
  4. Primary and secondary CTA text
  5. Testimonial/social proof suggestions
  6. Rationale for the approach taken in this variation
  7. Expected conversion characteristics of this variation

ab_testing_template: |
  Design an A/B testing plan for {{content_type}} focused on {{content_topic}} for {{company_name}}.

  ## Content Elements to Test
  - Element 1: {{element_1}} (e.g., headline, CTA, layout)
  - Element 2: {{element_2}} (optional)
  - Element 3: {{element_3}} (optional)

  ## Testing Parameters
  - Primary Conversion Goal: {{conversion_goal}}
  - Secondary Metrics to Track: {{secondary_metrics}}
  - Target Audience Segments: {{audience_segments}}
  - Test Duration: {{test_duration}}
  - Statistical Significance Target: {{significance_target}}

  ## Output Format
  Provide a comprehensive A/B testing plan including:
  1. Hypothesis for each variant (what you're testing and why)
  2. Detailed description of each variant (original vs. test versions)
  3. Expected impact on user behavior
  4. Sample size requirements for statistical validity
  5. Testing implementation recommendations
  6. Analysis framework for determining winner
  7. Recommendations for follow-up tests based on possible outcomes

examples:
  - role: "system"
    content: "You are the Content Creation & Testing Agent for GreenLife Organics, an advanced AI system specializing in generating high-quality marketing content and optimizing it through rigorous testing."
  
  - role: "user"
    content: |
      Create a high-quality blog post for GreenLife Organics on the topic of sustainable farming practices. Generate 3 distinct variations with different approaches to the topic.

      ## Content Brief
      - Primary Topic: Sustainable farming practices for home gardeners
      - Target Audience: Urban gardeners, ages 25-45, interested in organic food production
      - Primary Keyword: sustainable home gardening
      - Secondary Keywords: organic gardening tips, urban farming, sustainable agriculture
      - Target Word Count: 1200-1500 words
      - Call to Action: Sign up for GreenLife's upcoming virtual workshop on urban gardening
      - Key Messages: 
        1. Sustainable gardening is accessible for urban dwellers
        2. GreenLife Organics products support sustainable growing methods
        3. Small changes in gardening practices can have significant environmental impact

      ## Brand Guidelines
      Voice: Educational, enthusiastic, empowering
      Tone: Conversational, friendly expert
      Messaging Focus: Sustainability, accessibility, community
      Terminology: Use "growing methods" not "farming techniques", "earth-friendly" not "eco-friendly"
      Avoid: Technical jargon without explanation, discouraging language, exaggerated claims
  
  - role: "assistant"
    content: |
      # Blog Post Variations: Sustainable Farming Practices

      ## Variation 1: "The Urban Gardener's Guide to Sustainable Growing"

      ### Headline
      "Transform Your Urban Space: 7 Sustainable Home Gardening Methods Anyone Can Master"

      ### Meta Description
      Learn how to implement sustainable home gardening practices in any urban setting. These 7 earth-friendly growing methods will transform your space and reduce your environmental footprint.

      ### Full Blog Post
      [Complete 1400-word blog post with proper formatting, headings, and structure would appear here]

      ### Rationale
      This variation takes a practical, how-to approach focusing on actionable techniques readers can implement immediately. It's structured as a numbered list to increase readability and make the content more approachable for beginners. The content emphasizes the accessibility of sustainable practices in limited spaces, directly addressing potential objections from urban dwellers who may believe they lack sufficient space for meaningful gardening.

      ### Expected Performance
      This variation should perform well for search intent around specific techniques and how-to information. It's likely to generate higher time-on-page metrics as readers work through the detailed steps. The practical approach should drive strong conversion rates for the workshop CTA, as readers will be primed to deepen their practical knowledge.

      ## Variation 2: "The Environmental Impact of Your Garden Choices"

      ### Headline
      "Small Space, Big Impact: How Your Urban Garden Fights Climate Change"

      ### Meta Description
      Discover how sustainable home gardening practices in urban environments contribute to fighting climate change. Learn the environmental impact of your everyday gardening choices.

      ### Full Blog Post
      [Complete 1350-word blog post with proper formatting, headings, and structure would appear here]

      ### Rationale
      This variation takes an impact-focused approach, connecting personal actions to larger environmental benefits. It leverages the reader's likely interest in sustainability by quantifying the positive environmental impact of small-scale growing methods. This approach builds emotional investment by showing readers how their individual actions contribute to a larger movement.

      ### Expected Performance
      This variation should perform well with environmentally-conscious readers seeking purpose and meaning in their gardening practices. It's likely to generate higher share rates and social engagement as the content connects to larger social values. The purpose-driven approach may attract new audience segments interested in climate action beyond current gardeners.

      ## Variation 3: "From Novice to Expert: Your Sustainable Gardening Journey"

      ### Headline
      "Sustainable Home Gardening: From One Plant to Full Urban Farm in 12 Months"

      ### Meta Description
      Follow the journey from complete beginner to confident urban gardener using sustainable practices. This step-by-step progression makes sustainable home gardening accessible to everyone.

      ### Full Blog Post
      [Complete 1450-word blog post with proper formatting, headings, and structure would appear here]

      ### Rationale
      This variation takes a narrative, journey-based approach that meets readers wherever they are in their gardening experience. The progressive structure helps overcome intimidation barriers for beginners while still providing value to more experienced gardeners. By mapping out a year-long journey, it creates multiple entry points for readers of different experience levels.

      ### Expected Performance
      This variation should perform well for a broad audience range and have the longest content lifespan. The progression format encourages bookmarking and return visits as readers advance through their journey. It should generate strong workshop sign-ups as it naturally positions the workshop as the next step in the reader's learning progression.

      Would you like me to expand any specific section of these variations with the complete content?