http.host: "0.0.0.0"
xpack.monitoring.enabled: false

# Queue settings
queue.type: persisted
queue.max_bytes: 1gb

# Pipeline settings
pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50

# JVM Heap allocation
# Ensure you have enough memory for your workload
# Recommended to set to 50% of container memory
# -Xms256m -Xmx256m in environment variables