version: '3.8'

services:
  # Simple Health API
  health-api:
    build:
      context: .
      dockerfile: ./docker/health-api/Dockerfile.health-api
    ports:
      - "8001:8000"
    environment:
      - ENVIRONMENT=staging
    restart: always
    networks:
      - umt-network
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '256M'

  # API Gateway - Simplified version
  api-gateway:
    build:
      context: .
      dockerfile: ./docker/api_gateway/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=staging
      - LOG_LEVEL=INFO
      - USE_SIMPLIFIED_API=true
    volumes:
      - ./staging_main.py:/app/src/api/main.py  # Override with simplified version
    restart: always
    networks:
      - umt-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

networks:
  umt-network:
    driver: bridge
