version: '3.8'

services:
  # API Gateway
  api-gateway:
    build:
      context: .
      dockerfile: docker/api_gateway/Dockerfile
    ports:
      - "8000:8000"
    env_file: .env.staging
    environment:
      - ENVIRONMENT=staging
      - LOG_LEVEL=INFO
    depends_on:
      - postgres
      - redis
      - rabbitmq
    restart: always
    networks:
      - umt-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  # Frontend
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "3000:80"
    env_file: ./frontend/.env.staging
    depends_on:
      - api-gateway
    restart: always
    networks:
      - umt-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  # Agent Services
  auth-agent:
    build:
      context: .
      dockerfile: docker/agents/Dockerfile
    env_file: .env.staging
    environment:
      - AGENT_NAME=auth_integration_agent
      - ENVIRONMENT=staging
      - LOG_LEVEL=INFO
    depends_on:
      - rabbitmq
      - postgres
    restart: always
    networks:
      - umt-network
    command: ["python", "-m", "src.agents.runner"]
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  brand-agent:
    build:
      context: .
      dockerfile: docker/agents/Dockerfile
    env_file: .env.staging
    environment:
      - AGENT_NAME=brand_project_management_agent
      - ENVIRONMENT=staging
      - LOG_LEVEL=INFO
    depends_on:
      - rabbitmq
      - postgres
    restart: always
    networks:
      - umt-network
    command: ["python", "-m", "src.agents.runner"]
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  content-strategy-agent:
    build:
      context: .
      dockerfile: docker/agents/Dockerfile
    env_file: .env.staging
    environment:
      - AGENT_NAME=content_strategy_agent
      - ENVIRONMENT=staging
      - LOG_LEVEL=INFO
    depends_on:
      - rabbitmq
      - postgres
    restart: always
    networks:
      - umt-network
    command: ["python", "-m", "src.agents.runner"]
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  content-creation-agent:
    build:
      context: .
      dockerfile: docker/agents/Dockerfile
    env_file: .env.staging
    environment:
      - AGENT_NAME=content_creation_agent
      - ENVIRONMENT=staging
      - LOG_LEVEL=INFO
    depends_on:
      - rabbitmq
      - postgres
    restart: always
    networks:
      - umt-network
    command: ["python", "-m", "src.agents.runner"]
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  content-ad-agent:
    build:
      context: .
      dockerfile: docker/agents/Dockerfile
    env_file: .env.staging
    environment:
      - AGENT_NAME=content_ad_management_agent
      - ENVIRONMENT=staging
      - LOG_LEVEL=INFO
    depends_on:
      - rabbitmq
      - postgres
    restart: always
    networks:
      - umt-network
    command: ["python", "-m", "src.agents.runner"]
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  # Infrastructure Services
  postgres:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - umt-network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - umt-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - umt-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  vector-db:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${VECTOR_DB_USER}
      - POSTGRES_PASSWORD=${VECTOR_DB_PASSWORD}
      - POSTGRES_DB=${VECTOR_DB_NAME}
    volumes:
      - vector-db-data:/var/lib/postgresql/data
    networks:
      - umt-network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      
  # Database Migrations
  migrations:
    build:
      context: .
      dockerfile: docker/migrations/Dockerfile
    env_file: .env.staging
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}
      - PYTHONPATH=/app
      - ENVIRONMENT=staging
      - LOG_LEVEL=INFO
    depends_on:
      - postgres
    networks:
      - umt-network
    command: alembic upgrade head

networks:
  umt-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
  rabbitmq-data:
  vector-db-data: