version: '3.8'

services:
  # PostgreSQL database with pgvector extension
  postgres:
    image: postgres:17-alpine
    container_name: umt-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: umt
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - umt_network

  # Database migrations service
  migrations:
    build:
      context: .
      dockerfile: docker/migrations/Dockerfile
    container_name: umt-migrations
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/umt
      PYTHONPATH: /app
      UMT_ENV: staging
    depends_on:
      postgres:
        condition: service_healthy
    command: ["alembic", "upgrade", "head"]
    restart: "no"
    networks:
      - umt_network

  # Health monitoring API
  health-api:
    build:
      context: .
      dockerfile: monitoring/Dockerfile.health-api
    container_name: umt-health-api
    environment:
      POSTGRES_HOST: postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8001:8000"
    restart: unless-stopped
    networks:
      - umt_network

  # API Gateway - simplified version
  api-gateway:
    build:
      context: .
      dockerfile: docker/api_gateway/Dockerfile
    container_name: umt-api-gateway
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/umt
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: umt
      UMT_ENV: staging
      USE_SIMPLIFIED_API: "true"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - umt_network

volumes:
  postgres_data:

networks:
  umt_network:
    driver: bridge