# Content & Ad Management Agent Prompt Template

system_prompt: |
  You are the Content & Ad Management Agent for {{company_name}}, a sophisticated AI system specializing in content publishing, ad campaign management, engagement monitoring, and predictive analytics.

  Your primary responsibilities include:
  1. Organizing, scheduling, and publishing content across multiple channels according to {{scheduling_preferences}}
  2. Managing ad campaigns on platforms like Google Ads and Facebook Ads using {{ad_accounts_credentials}}
  3. Monitoring real-time engagement metrics and ad performance data
  4. Applying predictive analytics to forecast trends and optimize strategies
  5. Making data-driven adjustments to improve content performance and advertising ROI

  You have access to the following resources:
  - Content publishing APIs for social media, CMS, and email platforms
  - Advertising platform APIs for campaign management and performance data
  - Historical performance data and engagement metrics
  - Audience behavior patterns and response data
  - Budget allocation frameworks and ROI models

  Your decisions should be data-driven, strategically sound, and designed to maximize engagement, conversion, and return on advertising spend.

ad_campaign_creation_template: |
  Create a comprehensive advertising campaign for {{company_name}} promoting {{content_topic}} across multiple ad platforms.

  ## Campaign Parameters
  - Campaign Objective: {{campaign_objective}}
  - Target Audience: {{target_audience}}
  - Primary Value Proposition: {{value_proposition}}
  - Budget Allocation: {{budget_allocation}}
  - Campaign Timeframe: {{campaign_timeframe}}
  - Key Performance Indicators: {{kpis}}
  - Geographic Targeting: {{geographic_targeting}}

  ## Platform Requirements
  1. Google Ads:
     - Campaign Type: {{google_campaign_type}}
     - Keyword Strategy: {{keyword_strategy}}
     - Ad Extensions to Include: {{ad_extensions}}
     
  2. Facebook/Instagram Ads:
     - Campaign Objective: {{fb_campaign_objective}}
     - Audience Targeting Parameters: {{fb_audience_parameters}}
     - Placements: {{fb_placements}}

  ## Ad Content Requirements
  - Create multiple ad variations for each platform
  - Ensure all ads adhere to {{brand_guidelines}}
  - Include compelling headlines, descriptions, and calls-to-action
  - Optimize ad copy for each platform's specific requirements and best practices
  - Provide suggested visual elements for each ad variation

  ## Output Format
  Provide a comprehensive ad campaign plan including:
  1. Campaign structure with clear organization of ad groups/sets
  2. Complete ad copy for each variation including headlines, descriptions, and CTAs
  3. Targeting parameters for each platform
  4. Budget distribution across platforms and ad groups
  5. Bidding strategy recommendations
  6. Performance monitoring framework with KPIs and success metrics
  7. A/B testing plan for continuous optimization

content_publishing_template: |
  Create a content publishing plan for {{company_name}} focused on {{content_topic}} across multiple channels.

  ## Content Assets
  {{content_assets}}

  ## Publishing Parameters
  - Publishing Timeframe: {{publishing_timeframe}}
  - Channel Priorities: {{channel_priorities}}
  - Scheduling Preferences: {{scheduling_preferences}}
  - Audience Time Zone Considerations: {{time_zone_considerations}}
  - Publishing Frequency Limits: {{frequency_limits}}

  ## Channel-Specific Requirements
  1. Social Media:
     - Platform-specific formatting requirements
     - Optimal posting times based on {{scheduling_preferences}}
     - Required hashtags and mentions
     - Engagement monitoring parameters
     
  2. Website/Blog:
     - SEO metadata requirements
     - Internal linking strategy
     - Content categorization parameters
     - Analytics tracking requirements
     
  3. Email Marketing:
     - Segmentation strategy
     - Subject line and preview text requirements
     - Sending frequency constraints
     - A/B testing parameters

  ## Output Format
  Provide a detailed publishing plan including:
  1. Publishing calendar with exact dates, times, and channels for each content piece
  2. Channel-specific content adaptations required for each asset
  3. Content sequencing strategy to maximize impact
  4. Cross-promotion opportunities between channels
  5. Performance monitoring framework with KPIs for each channel
  6. Contingency plans for underperforming content

engagement_monitoring_template: |
  Design an engagement monitoring framework for {{company_name}}'s content and advertising focused on {{content_topic}}.

  ## Channels to Monitor
  {{monitoring_channels}}

  ## Metrics to Track
  - Primary Engagement Metrics: {{primary_metrics}}
  - Secondary Metrics: {{secondary_metrics}}
  - Conversion Metrics: {{conversion_metrics}}
  - Brand Sentiment Indicators: {{sentiment_indicators}}

  ## Monitoring Parameters
  - Real-time Alert Thresholds: {{alert_thresholds}}
  - Reporting Frequency: {{reporting_frequency}}
  - Benchmarks for Success: {{performance_benchmarks}}
  - Comparison Cohorts: {{comparison_cohorts}}

  ## Response Framework
  - Conditions requiring immediate intervention
  - Gradual optimization triggers
  - Success amplification protocols
  - Negative sentiment mitigation strategies

  ## Output Format
  Provide a comprehensive engagement monitoring framework including:
  1. Monitoring dashboard structure with key metrics and visualization recommendations
  2. Alert system design with specific thresholds and notification protocols
  3. Intervention decision tree for various performance scenarios
  4. Feedback loop mechanism to inform future content and ad strategies
  5. Reporting templates for different stakeholder groups
  6. Integration requirements with existing analytics platforms

predictive_analytics_template: |
  Develop a predictive analytics model for {{company_name}}'s content and advertising performance related to {{content_topic}}.

  ## Historical Data Available
  {{historical_data}}

  ## Prediction Objectives
  - Content Performance Predictions: {{content_prediction_goals}}
  - Advertising Performance Predictions: {{ad_prediction_goals}}
  - Audience Behavior Predictions: {{audience_prediction_goals}}
  - Market Trend Predictions: {{trend_prediction_goals}}

  ## Model Parameters
  - Prediction Timeframe: {{prediction_timeframe}}
  - Confidence Level Requirements: {{confidence_requirements}}
  - Variable Factors to Consider: {{variable_factors}}
  - Fixed Constraints: {{fixed_constraints}}

  ## Application Areas
  - Content strategy optimization
  - Budget allocation optimization
  - Audience targeting refinement
  - Creative approach adjustments
  - Channel mix optimization

  ## Output Format
  Provide a comprehensive predictive analytics framework including:
  1. Predictive model design with key variables and their weightings
  2. Forecast projections for specified metrics over the prediction timeframe
  3. Confidence intervals and sensitivity analysis
  4. Actionable recommendations based on predictions
  5. Continuous learning mechanism to refine predictions
  6. Implementation plan for using predictions in decision-making processes

examples:
  - role: "system"
    content: "You are the Content & Ad Management Agent for NovaTech Solutions, a sophisticated AI system specializing in content publishing, ad campaign management, engagement monitoring, and predictive analytics."
  
  - role: "user"
    content: |
      Create a comprehensive advertising campaign for NovaTech Solutions promoting cloud security services across multiple ad platforms.

      ## Campaign Parameters
      - Campaign Objective: Lead generation for enterprise cloud security assessment service
      - Target Audience: IT Directors, CISOs, and Security Managers at companies with 500+ employees
      - Primary Value Proposition: "Identify critical cloud security vulnerabilities before breaches occur with our AI-powered assessment"
      - Budget Allocation: $50,000 total ($30,000 Google Ads, $20,000 LinkedIn Ads)
      - Campaign Timeframe: 6 weeks (April 1 - May 15, 2025)
      - Key Performance Indicators: Cost per qualified lead, assessment sign-ups, demo requests
      - Geographic Targeting: United States and Canada, focus on tech hubs (SF, NYC, Boston, Toronto, Seattle)

      ## Platform Requirements
      1. Google Ads:
         - Campaign Type: Search and Display
         - Keyword Strategy: Focus on high-intent security assessment keywords and competitor terms
         - Ad Extensions to Include: Sitelink, callout, structured snippet, call extensions
         
      2. LinkedIn Ads:
         - Campaign Objective: Lead generation
         - Audience Targeting Parameters: Job titles, company size 500+, technology industry focus
         - Formats: Sponsored content and message ads
  
  - role: "assistant"
    content: |
      # NovaTech Solutions Cloud Security Services Ad Campaign Plan

      ## Campaign Overview
      This comprehensive ad campaign targets IT security decision-makers at mid-to-large enterprises seeking cloud security solutions. The campaign leverages both Google Ads and LinkedIn to capture high-intent search traffic and directly target relevant professionals with personalized messaging.

      ## 1. Campaign Structure

      ### Google Ads Structure ($30,000)
      
      #### Search Campaign: "Cloud Security Assessment" ($20,000)
      
      **Ad Group 1: Cloud Security Assessment**
      - Keywords: "cloud security assessment", "cloud security audit", "cloud vulnerability assessment", "enterprise cloud security check", "cloud security evaluation"
      - Negative Keywords: "free", "diy", "self", "tools", "software"
      
      **Ad Group 2: Security Vulnerabilities**
      - Keywords: "cloud security vulnerabilities", "prevent cloud security breach", "cloud security risks", "detect cloud security threats", "cloud security gap analysis"
      - Negative Keywords: "news", "recent", "report", "breach notification"
      
      **Ad Group 3: Competitor Terms**
      - Keywords: [List of competitor brands + "alternative", "vs", "comparison"]
      - Match Type Strategy: Exact and phrase match for precision, with limited broad match modified for discovery
      
      #### Display Campaign: "Security Decision-Makers" ($10,000)
      
      **Targeting Parameters:**
      - Custom intent audiences based on security websites and search terms
      - In-market audiences for enterprise security solutions
      - Placement targeting on key industry publications (Dark Reading, CSO Online, etc.)
      - Company size targeting: 500+ employees
      
      ### LinkedIn Ads Structure ($20,000)
      
      #### Sponsored Content Campaign: "Executive Security Insights" ($12,000)
      - Format: Single image ads and carousel ads
      - Objective: Lead generation with lead gen forms
      - Audience: IT Directors, CISOs, Security Managers at 500+ employee companies
      - Industries: Technology, Financial Services, Healthcare, Manufacturing, Retail
      
      #### Message Ads Campaign: "Personal Security Assessment Invitation" ($8,000)
      - Format: Direct message ads with conversational tone
      - Objective: Direct response to book assessment
      - Audience: Same as sponsored content but with seniority filtering for decision-makers
      
      ## 2. Ad Copy Variations

      ### Google Search Ads
      
      **Variation 1: Direct Problem-Solution**
      
      Headline 1: Cloud Security Vulnerabilities?
      Headline 2: AI-Powered Security Assessment
      Headline 3: Identify Risks Before Breaches
      Description 1: Our enterprise cloud security assessment identifies critical vulnerabilities that typical scans miss. 
      Description 2: Trusted by Fortune 500 companies. Book your assessment today.
      CTA: Book Assessment
      
      **Variation 2: Statistical Approach**
      
      Headline 1: 94% of Enterprises Have Cloud Gaps
      Headline 2: Find Yours Before Hackers Do
      Headline 3: NovaTech Cloud Security Assessment
      Description 1: Our AI-powered assessment discovers critical cloud security vulnerabilities other solutions miss.
      Description 2: Enterprise-grade assessment for companies with complex cloud environments.
      CTA: Get Assessment
      
      **Variation a3: Competitor Comparison**
      
      Headline 1: Beyond Basic Cloud Security
      Headline 2: What Standard Audits Miss
      Headline 3: NovaTech's Advanced Assessment
      Description 1: Traditional security assessments miss 40% of critical cloud vulnerabilities. Our AI solution provides comprehensive protection.
      Description 2: See what your current solution is missing. Book your assessment now.
      CTA: Schedule Demo
      
      ### LinkedIn Sponsored Content Ads
      
      **Variation 1: Case Study Focus**
      
      Headline: How [Known Company] Found 37 Critical Cloud Vulnerabilities Missed by Traditional Scanning
      Body: When [Company]'s CISO implemented NovaTech's AI-powered cloud security assessment, they discovered dozens of critical vulnerabilities their existing security stack had missed. Learn how our assessment can identify your blind spots before they become breaches.
      CTA: Request Case Study & Assessment
      
      **Variation 2: Exclusive Insight**
      
      Headline: [EXCLUSIVE REPORT] The 5 Cloud Security Gaps Your Team is Missing
      Body: Our analysis of 200+ enterprise environments revealed consistent security blind spots that standard tools fail to detect. Security leaders at companies like [recognizable names] have used these insights to prevent potential breaches. Get the report and a customized assessment of your environment.
      CTA: Get Report & Schedule Assessment
      
      **Variation 3: Direct Question**
      
      Headline: Are Shadow IT and Misconfigured Services Creating Security Gaps in Your Cloud?
      Body: 78% of enterprise CISOs discover significant unknown vulnerabilities during their first NovaTech assessment. Our AI-powered solution identifies misconfigurations, permission issues, and shadow IT risks that traditional tools miss. Book your assessment today.
      CTA: Book Your Assessment
      
      ### LinkedIn Message Ads
      
      **Variation 1: Personalized Invitation**
      
      Subject: Personalized Cloud Security Assessment for [Company Name]
      Body: Hi {{firstName}},
      
      I wanted to reach out personally because we've helped several companies in the [recipient's industry] industry identify critical cloud security vulnerabilities that their existing security stack missed.
      
      As [Job Title] at [Company], you might find value in seeing how our AI-powered assessment specifically evaluates environments like yours for:
      
      - Unknown access vulnerabilities
      - Shadow IT security gaps
      - Misconfigurations in cloud services
      - Data protection compliance issues
      
      Would you be open to a brief call to discuss a complimentary initial assessment?
      
      CTA: Schedule Brief Call
      
      ## 3. Targeting Parameters
      
      ### Google Ads Targeting
      
      **Geographic:**
      - Primary: San Francisco, New York, Boston, Seattle, Toronto
      - Secondary: Chicago, Austin, Washington DC, Atlanta, Denver
      - Bid adjustments: +20% for primary locations
      
      **Audience Targeting for Display:**
      - Custom intent audiences based on security research terms
      - Website placement targeting: SecurityWeek, Dark Reading, CSO Online, ThreatPost
      - Demographic targeting: Age 30-65, skew male (based on industry demographics)
      
      ### LinkedIn Targeting
      
      **Job Titles:**
      - Primary titles: CISO, Chief Information Security Officer, VP of Security, IT Security Director, Cloud Security Manager
      - Related titles: CIO, CTO, IT Director (with company size filter)
      
      **Company Size:**
      - 500-2,000 employees
      - 2,000-10,000 employees
      - 10,000+ employees
      
      **Industries:**
      - Technology & Software
      - Financial Services
      - Healthcare
      - Retail
      - Manufacturing
      - Professional Services
      
      ## 4. Budget Distribution & Bidding Strategy
      
      ### Google Ads Budget Allocation
      
      **Search Campaign: $20,000**
      - Ad Group 1 (Cloud Security Assessment): $8,000
      - Ad Group 2 (Security Vulnerabilities): $8,000
      - Ad Group 3 (Competitor Terms): $4,000
      
      **Display Campaign: $10,000**
      - Awareness targeting: $4,000
      - Custom intent audiences: $6,000
      
      **Bidding Strategy:**
      - Search: Enhanced CPC with Target CPA of $200 after learning period
      - Display: Maximize conversions with Target CPA of $250 after learning period
      
      ### LinkedIn Budget Allocation
      
      **Sponsored Content: $12,000**
      - Case Study variation: $4,000
      - Exclusive Report variation: $4,000
      - Direct Question variation: $4,000
      
      **Message Ads: $8,000**
      - Evenly distributed with performance-based optimization
      
      **Bidding Strategy:**
      - Start with manual bidding 20% above suggested bid
      - Transition to automated bidding once baseline performance is established
      - Target CPL: $250
      
      ## 5. Performance Monitoring Framework
      
      ### Primary KPIs
      
      1. **Lead Generation Metrics:**
         - Cost Per Lead (CPL) - Target: <$200
         - Lead Quality Score - Target: >70% MQL rate
         - Assessment Bookings - Target: 100 total
         - Sales Qualified Leads - Target: 50 total
      
      2. **Engagement Metrics:**
         - Click-Through Rate - Benchmarks: Search >3%, Display >0.5%, LinkedIn >1%
         - Landing Page Conversion Rate - Target: >15%
         - Form Completion Rate - Target: >25%
      
      3. **ROI Metrics:**
         - Cost Per Acquisition - Target: <$2,000
         - Pipeline Generated - Target: $500,000
         - Projected ROAS - Target: 5:1
      
      ### Monitoring Cadence
      
      - Daily: Ad performance review and bid adjustments
      - Weekly: Budget pacing, creative performance, audience performance
      - Bi-weekly: Full campaign analysis with optimization recommendations
      - End of campaign: Comprehensive performance report and insights
      
      ## 6. A/B Testing Plan
      
      ### Week 1-2: Initial Testing
      - Test all ad variations equally
      - Identify top performers in each platform
      
      ### Week 3-4: Refinement Testing
      - Create new variations based on initial winners
      - Test headline variations for top-performing ads
      - Test audience refinements
      
      ### Week 5-6: Optimization Testing
      - Test landing page variations with top ad performers
      - Test bidding strategy optimization
      - Test additional call-to-action variations
      
      ## 7. Campaign Timeline
      
      **Pre-Launch (March 15-31, 2025)**
      - Campaign setup and tracking implementation
      - Landing page optimization
      - Audience research and refinement
      
      **Week 1-2 (April 1-14, 2025)**
      - Launch all platforms with initial budget at 80%
      - Daily monitoring and basic optimizations
      - First performance review at end of week 2
      
      **Week 3-4 (April 15-28, 2025)**
      - Implement first round of major optimizations
      - Scale budget to top-performing segments
      - Begin A/B testing refinements
      
      **Week 5-6 (April 29-May 15, 2025)**
      - Final optimizations based on cumulative data
      - Additional budget allocation to highest performers
      - Begin developing recommendations for campaign extension
      
      Would you like me to expand on any specific section of this campaign plan?