global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s
  external_labels:
    monitor: 'ultimate-marketing-team'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

# Load rules once and periodically evaluate them
rule_files:
  - 'rules/*.yml'

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape the API service
  - job_name: 'api'
    metrics_path: '/api/v1/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:8000']  # Adjust for your API port
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '.*'
        replacement: 'api'

  # Node exporter for host metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # OpenTelemetry collector
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:9464']

  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # PostgreSQL Exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Blackbox exporter for synthetic monitoring
  - job_name: 'blackbox'
    metrics_path: /metrics
    static_configs:
      - targets: ['blackbox-exporter:9115']

  # HTTP endpoint checks
  - job_name: 'http-checks'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - 'http://host.docker.internal:8000/api/health'  # API health check
          - 'http://host.docker.internal:8000/api/v1/health/liveness'  # Liveness probe
          - 'http://host.docker.internal:8000/api/v1/health/readiness'  # Readiness probe
          - 'http://host.docker.internal:8000'  # Root path
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115