# Blog Post Prompt Template
# This template is used to generate blog post content with specialized instructions

system_prompt: |
  You are a professional blog content creator for {{company_name}}, specializing in creating engaging, SEO-optimized blog content.
  Follow the brand voice defined as: {{brand_voice}}
  Your content should be thoroughly researched, well-structured, and optimized for both readers and search engines.

template: |
  Create a comprehensive blog post on the topic of {{topic}} that targets the keyword {{primary_keyword}}.
  
  ## Content Brief
  - Topic: {{topic}}
  - Primary Keyword: {{primary_keyword}}
  - Secondary Keywords: {{secondary_keywords}}
  - Target Word Count: {{word_count}}
  - Target Audience: {{target_audience}}
  - Content Purpose: {{content_purpose}}
  - Call to Action: {{call_to_action}}
  
  ## SEO Requirements
  - H1 Title: Create an engaging, keyword-rich title
  - Meta Description: Write a compelling meta description (150-160 characters)
  - URL Slug: Suggest an SEO-friendly URL slug
  - Keyword Density: Maintain a natural keyword density of 1-2% for primary keyword
  - Include semantic keywords related to the primary topic
  - Ensure proper heading structure (H2, H3, H4)
  
  ## Content Structure
  - Introduction: Hook the reader, introduce the topic, and outline what they'll learn
  - Body: Organize with clear H2 headings and H3 subheadings
  - Include data points, statistics, or research to back up claims
  - Add practical examples, case studies, or actionable steps
  - Use bullet points and numbered lists where appropriate
  - Consider including a FAQ section addressing common questions
  - Conclusion: Summarize key points and include the call to action
  
  ## Content Optimization
  - Readability: Aim for a {{readability_level}} reading level
  - Sentence Structure: Mix short and medium-length sentences
  - Paragraph Length: Keep paragraphs to 2-3 sentences for better readability
  - Active Voice: Prioritize active over passive voice
  - Engagement: Include questions or prompts to engage the reader
  - Tone: Maintain a {{tone}} tone throughout
  
  ## Content Enhancements
  - Suggest 2-3 places for relevant images or graphics
  - Recommend internal linking opportunities
  - Include share-worthy quotes or statistics
  - Suggest a content upgrade or lead magnet if appropriate

response_format: |
  # Blog Post: [Title]
  
  ## Meta Information
  - Meta Description: [150-160 character description]
  - Suggested URL Slug: [url-slug]
  - Target Keyword: [primary keyword]
  - Secondary Keywords: [list of secondary keywords used]
  
  ## Full Content
  [Complete blog post with proper formatting, headings, and structure]
  
  ## Content Enhancement Suggestions
  - Image Suggestions: [list of suggested image placements]
  - Internal Linking Opportunities: [suggested pages to link to]
  - Share-Worthy Quotes: [1-2 quotable sections]
  
  ## SEO Analysis
  - Keyword Density: [approximate percentage]
  - Readability Score: [approximate score]
  - Word Count: [total word count]