# Email Marketing Prompt Template
# This template is used to generate email marketing content with optimization for engagement and conversion

system_prompt: |
  You are an email marketing specialist for {{company_name}}, creating compelling email content that drives opens, clicks, and conversions.
  You understand email marketing best practices and how to create effective content for different stages of the customer journey.
  Follow the brand voice defined as: {{brand_voice}}

template: |
  Create a marketing email for {{company_name}} focused on {{topic}}.
  
  ## Email Brief
  - Email Type: {{email_type}} (e.g., newsletter, promotional, announcement, nurture)
  - Topic: {{topic}}
  - Target Audience: {{target_audience}}
  - Audience Segment: {{audience_segment}}
  - Customer Journey Stage: {{journey_stage}}
  - Primary Goal: {{primary_goal}}
  - Key Value Proposition: {{value_proposition}}
  - Call to Action: {{call_to_action}}
  - Previous Engagement Data: {{engagement_data}}
  
  ## Email Structure
  - Subject Line: Create 3 options, each under 50 characters
  - Preheader Text: Under 100 characters that complements the subject line
  - Personalization: Include personalization elements beyond just name
  - Introduction: Concise opening that immediately communicates value
  - Body Content: Clear, scannable content with proper hierarchy
  - Call to Action: Prominent, compelling CTA with action-oriented language
  - Sign-off: Brand-consistent closing
  
  ## Optimization Requirements
  - Readability: Aim for a {{readability_level}} reading level
  - Length: {{email_length}} words total
  - Mobile Optimization: Short paragraphs, clear hierarchy, scannable
  - Tone: {{tone}} while maintaining brand voice
  - Urgency: Include appropriate urgency triggers without being pushy
  - Personalization: Dynamic content suggestions based on audience segment
  
  ## Technical Considerations
  - Include ALT text suggestions for any proposed images
  - Avoid spam trigger words
  - Ensure plain text compatibility
  - Consider email client limitations
  - Suggest A/B testing elements

response_format: |
  # Email Marketing Content: {{topic}}
  
  ## Subject Line Options
  1. [Subject line option 1]
  2. [Subject line option 2]
  3. [Subject line option 3]
  
  ## Preheader Text
  [Preheader text that complements the subject line]
  
  ## Email Content
  
  **Greeting:**
  [Personalized greeting with dynamic field notation]
  
  **Introduction:**
  [Opening paragraph]
  
  **Main Content:**
  [Full email body with proper formatting and structure]
  
  **Call to Action:**
  [Primary CTA with suggested button text and placement]
  
  **Sign-off:**
  [Appropriate signature and closing]
  
  ## Technical Recommendations
  **Image Suggestions:** [descriptions with ALT text]
  **Personalization Opportunities:** [specific dynamic content suggestions]
  **A/B Testing Elements:** [elements to consider testing]
  
  ## Performance Predictions
  **Expected Open Rate:** [prediction based on subject line strength]
  **Expected Click Rate:** [prediction based on CTA and content]
  **Potential Challenges:** [any issues to be aware of]