# Social Media Prompt Template
# This template is used to generate social media content with platform-specific instructions

system_prompt: |
  You are a social media content specialist for {{company_name}}, creating engaging, platform-optimized content that drives engagement.
  You understand the nuances of each social platform and know how to tailor content accordingly.
  Follow the brand voice defined as: {{brand_voice}}

template: |
  Create a set of social media posts about {{topic}} for distribution across multiple platforms.
  
  ## Content Brief
  - Topic: {{topic}}
  - Key Message: {{key_message}}
  - Campaign Goal: {{campaign_goal}}
  - Target Audience: {{target_audience}}
  - Call to Action: {{call_to_action}}
  - Hashtags to Consider: {{hashtags}}
  - Campaign Period: {{campaign_period}}
  
  ## Platform Requirements
  
  ### LinkedIn
  - Professional tone with thought leadership positioning
  - 1200-1500 characters maximum
  - Focus on industry insights and value proposition
  - Include 2-3 targeted hashtags
  - Suggest a poll or question to drive engagement
  
  ### Twitter
  - Concise, attention-grabbing copy under 280 characters
  - Incorporate trending, relevant hashtags (2-3 max)
  - Include a clear call to action
  - Consider adding a question to encourage replies
  - Format for readability (spacing, line breaks)
  
  ### Instagram
  - Visual-first approach with supporting caption up to 125 words
  - Front-load important content before the "more" cutoff
  - Incorporate storytelling elements
  - Use a mix of hashtags (3 visible in caption, 15-20 after line breaks)
  - Include emoji for visual appeal
  
  ### Facebook
  - Conversational, community-focused content
  - 100-250 words with clear paragraph breaks
  - Include a question or prompt for comments
  - Minimal hashtag usage (2-3 maximum)
  - Consider native video/image carousel suggestions
  
  ## Content Optimization
  - Maintain consistent brand voice while adapting to each platform
  - Create content that encourages sharing and engagement
  - Ensure each post stands alone but aligns with the campaign
  - Incorporate social listening insights: {{social_listening_insights}}
  - Reference previous high-performing content themes: {{top_performing_themes}}
  
  ## Visual Recommendations
  For each platform, provide a brief description of the ideal visual to accompany the post.

response_format: |
  # Social Media Content Package: {{topic}}
  
  ## LinkedIn Post
  [Complete LinkedIn post with proper formatting]
  
  **Suggested Hashtags:** [hashtags]
  **Visual Recommendation:** [brief description of ideal visual]
  **Engagement Strategy:** [suggestion to increase engagement]
  
  ## Twitter Post
  [Complete Twitter post within character limit]
  
  **Suggested Hashtags:** [hashtags]
  **Visual Recommendation:** [brief description of ideal visual]
  **Thread Opportunity:** [Yes/No with suggestion if applicable]
  
  ## Instagram Caption
  [Complete Instagram caption with proper formatting]
  
  **Visible Hashtags:** [2-3 hashtags to include in main text]
  **Additional Hashtags:** [additional hashtags to add after line breaks]
  **Visual Recommendation:** [brief description of ideal visual]
  **Story Content:** [suggestion for complementary story content]
  
  ## Facebook Post
  [Complete Facebook post with proper formatting]
  
  **Suggested Hashtags:** [hashtags]
  **Visual Recommendation:** [brief description of ideal visual]
  **Engagement Question:** [specific question to encourage comments]