# Ultimate Marketing Team Platform - Integrations Configuration

# Social Media Platform Integrations
social_media:
  facebook:
    api_version: "v18.0"
    required_permissions:
      - pages_manage_posts
      - pages_read_engagement
      - instagram_basic
      - instagram_content_publish
    rate_limits:
      requests_per_hour: 200
      posts_per_day: 25
    webhooks:
      - event: page_post_engagement
        endpoint: /api/webhooks/facebook/engagement
      - event: instagram_comment
        endpoint: /api/webhooks/instagram/comments
    error_handling:
      retry_attempts: 3
      retry_delay_seconds: 60

  twitter:
    api_version: "2.0"
    required_permissions:
      - tweet.read
      - tweet.write
      - users.read
    rate_limits:
      requests_per_hour: 300
      tweets_per_day: 50
    webhooks:
      - event: tweet_create
        endpoint: /api/webhooks/twitter/tweet_create
      - event: tweet_engagement
        endpoint: /api/webhooks/twitter/engagement
    error_handling:
      retry_attempts: 3
      retry_delay_seconds: 30

  linkedin:
    api_version: "v2"
    required_permissions:
      - w_member_social
      - r_organization_social
    rate_limits:
      requests_per_hour: 100
      posts_per_day: 15
    error_handling:
      retry_attempts: 3
      retry_delay_seconds: 120

# Content Management System Integrations
cms:
  wordpress:
    api_version: "wp/v2"
    required_permissions:
      - create_posts
      - edit_posts
      - upload_files
    content_types:
      - post
      - page
      - custom_post_type
    media_handling:
      max_file_size_mb: 10
      supported_formats:
        - jpg
        - png
        - gif
        - pdf
    error_handling:
      retry_attempts: 3
      retry_delay_seconds: 30

  shopify:
    api_version: "2023-10"
    required_permissions:
      - write_content
      - read_content
      - write_products
    content_types:
      - blog
      - page
      - product_description
    rate_limits:
      requests_per_minute: 40
    error_handling:
      retry_attempts: 3
      retry_delay_seconds: 45

# Advertising Platform Integrations
advertising:
  google_ads:
    api_version: "v14"
    required_permissions:
      - CAMPAIGN_MANAGEMENT
      - ACCOUNT_MANAGEMENT
      - REPORTING
    entity_types:
      - campaign
      - ad_group
      - ad
      - keyword
    reporting:
      metrics:
        - impressions
        - clicks
        - conversions
        - cost
      dimensions:
        - date
        - campaign
        - ad_group
        - device
    budget_management:
      min_daily_budget_usd: 5.00
      alert_threshold_percentage: 85
    error_handling:
      retry_attempts: 3
      retry_delay_seconds: 60

  facebook_ads:
    api_version: "v18.0"
    required_permissions:
      - ads_management
      - ads_read
      - business_management
    entity_types:
      - campaign
      - ad_set
      - ad
    reporting:
      metrics:
        - impressions
        - reach
        - clicks
        - spend
        - actions
      dimensions:
        - time
        - campaign_name
        - age
        - gender
        - placement
    audience_targeting:
      min_audience_size: 1000
    error_handling:
      retry_attempts: 3
      retry_delay_seconds: 45

# Analytics Platform Integrations
analytics:
  google_analytics:
    api_version: "GA4"
    required_permissions:
      - EDIT
      - READ_AND_ANALYZE
    metrics:
      - screenPageViews
      - sessions
      - conversions
      - eventCount
    dimensions:
      - date
      - deviceCategory
      - country
      - source
      - medium
    reporting:
      max_days_range: 90
      sampling_level: LARGE
    error_handling:
      retry_attempts: 3
      retry_delay_seconds: 30

  custom_analytics:
    enabled: true
    tracking:
      pageviews: true
      events: true
      conversions: true
      user_sessions: true
    retention:
      data_storage_days: 365
    export:
      formats:
        - csv
        - json
      scheduled_reports: true

# Email Marketing Platform Integrations
email:
  mailchimp:
    api_version: "3.0"
    required_permissions:
      - campaigns:write
      - campaigns:read
      - lists:write
      - lists:read
    features:
      - campaigns
      - segments
      - templates
      - automations
    metrics:
      - opens
      - clicks
      - bounces
      - unsubscribes
    rate_limits:
      sends_per_day: 12000
    error_handling:
      retry_attempts: 3
      retry_delay_seconds: 30

  sendgrid:
    api_version: "v3"
    required_permissions:
      - mail.send
      - stats.read
      - marketing.campaigns.read
      - marketing.campaigns.update
    features:
      - transactional
      - marketing
      - templates
      - segments
    metrics:
      - delivered
      - opened
      - clicked
      - bounced
    rate_limits:
      sends_per_day: 10000
    error_handling:
      retry_attempts: 3
      retry_delay_seconds: 30

# AI Services Integration
ai_services:
  openai:
    models:
      - name: gpt-4-turbo
        max_tokens: 128000
        primary_use: "content_creation_complex"
        cost_per_1k_tokens_input: 0.01
        cost_per_1k_tokens_output: 0.03
      - name: gpt-3.5-turbo
        max_tokens: 16385
        primary_use: "content_optimization"
        cost_per_1k_tokens_input: 0.0015
        cost_per_1k_tokens_output: 0.002
    rate_limits:
      requests_per_minute: 500
      tokens_per_minute: 300000
    error_handling:
      retry_attempts: 3
      retry_delay_seconds: 10

  anthropic:
    models:
      - name: claude-3-opus
        max_tokens: 200000
        primary_use: "strategy_generation"
        cost_per_1k_tokens_input: 0.015
        cost_per_1k_tokens_output: 0.075
      - name: claude-3-sonnet
        max_tokens: 200000
        primary_use: "competitor_analysis"
        cost_per_1k_tokens_input: 0.003
        cost_per_1k_tokens_output: 0.015
    rate_limits:
      requests_per_minute: 300
      tokens_per_minute: 150000
    error_handling:
      retry_attempts: 3
      retry_delay_seconds: 10

  self_hosted:
    models:
      - name: llama-3-70b
        server: "http://ai-cluster.internal:8080"
        max_tokens: 8192
        primary_use: "high_volume_content_generation"
      - name: mistral-7b-instruct
        server: "http://ai-cluster.internal:8081"
        max_tokens: 4096
        primary_use: "content_classification"
    rate_limits:
      requests_per_minute: 1000
    error_handling:
      retry_attempts: 3
      retry_delay_seconds: 5

# Global Integration Settings
global:
  logging:
    enabled: true
    level: INFO
    retention_days: 30
  monitoring:
    health_checks:
      interval_seconds: 300
      timeout_seconds: 30
    alerts:
      email: "alerts@company.com"
      slack_webhook: "https://hooks.slack.com/services/XXX/YYY/ZZZ"
  security:
    api_key_rotation_days: 90
    oauth_token_expiry_hours: 24
    ip_whitelist_enabled: true
  fallback_strategy:
    enabled: true
    max_retries: 5
    alternative_service_routing: true