user_authentication_task:
  description: >
    Authenticate users securely through multiple social platforms using {social_accounts_credentials} 
    which include OAuth tokens and API keys for various social media platforms. Verify account 
    integrity, establish secure sessions, implement appropriate security measures including 
    MFA where available, and maintain secure token storage. Handle authentication errors 
    gracefully and provide clear user feedback for troubleshooting.
  expected_output: >
    Complete authentication flow with secure token management, user profile creation/retrieval, 
    and appropriate session establishment. Provide confirmation of successful authentication 
    with platform-specific user identifiers or specific error information for troubleshooting. 
    Generate comprehensive authentication logs for security auditing and token refresh management.
  agent: auth_integration_agent

platform_integration_setup_task:
  description: >
    Configure and test integrations with external platforms using {CMS_credentials} for content 
    management systems like WordPress and Shopify, and {ad_accounts_credentials} for advertising 
    networks including Google Ads and Facebook Ads. Establish API connections, verify access 
    permissions, test data exchange capabilities, and configure webhook connections where 
    applicable. Implement comprehensive monitoring for connection health and API rate limits.
  expected_output: >
    Successfully established connections with all specified platforms, verified through test 
    transactions. Generate platform-specific configuration documentation including API endpoints, 
    authentication methods, data mapping schemas, webhook URLs, and rate limit parameters. 
    Deliver integration health monitoring dashboard with real-time status indicators and 
    automated alerting for API issues.
  agent: auth_integration_agent

brand_onboarding_task:
  description: >
    Capture essential brand information including {company_name} and comprehensive {brand_guidelines} 
    covering voice, tone, visual identity, messaging frameworks, and approved terminology. 
    Create structured brand profiles with all visual assets and style parameters. Automatically 
    enrich brand profiles by crawling and analyzing the brand's website at {website_url} to 
    extract additional insights about brand positioning, content structure, visual elements, 
    and audience targeting approaches.
  expected_output: >
    Complete brand profile with structured representation of {brand_guidelines} including tone 
    of voice parameters, visual identity elements, messaging architecture, terminology standards, 
    and approval workflows. Supplementary data extracted from {website_url} analysis including 
    color schemes, font usage patterns, key messaging themes, existing content categories, and 
    audience targeting indicators. Generate verification report confirming successful brand 
    onboarding with all required elements.
  agent: brand_project_management_agent

project_setup_task:
  description: >
    Establish project frameworks for multiple {project_types} (Email, Landing Page, Social Post, 
    Blog) within each brand profile. Configure project-specific parameters, templates, content 
    requirements, workflow stages, and approval processes appropriate for each project type. 
    Implement role-based access controls for team members based on project type and create 
    comprehensive audit trails for all project activities.
  expected_output: >
    Fully configured project workspaces for each {project_types} with customized templates, 
    workflow definitions, role assignments, and milestone schedules. Generate project setup 
    confirmation report detailing structures created, access permissions established, and 
    available templates for each project type. Include audit logging configuration verification 
    and project-specific completion checklists for each {project_types}.
  agent: brand_project_management_agent

content_strategy_development_task:
  description: >
    Analyze target audience data, {content_topic} relevance, and {performance_metrics} 
    (including engagement, reach, SEO, and ad performance data) from previous content 
    initiatives to develop comprehensive content strategy recommendations. Identify key 
    themes, messaging approaches, content formats, and distribution channels most likely 
    to achieve business objectives for each {project_types} while resonating with target 
    audiences.
  expected_output: >
    Strategic content plan document outlining recommended content themes, formats, and 
    distribution approaches based on audience analysis and {performance_metrics}. Include 
    specific KPIs for measuring content effectiveness across different {project_types}, 
    content pillar structure organized by {content_topic}, and audience segment targeting 
    approach. Provide data-backed rationale for all strategic recommendations with 
    references to specific {performance_metrics}.
  agent: content_strategy_research_agent

competitor_analysis_task:
  description: >
    Conduct thorough analysis of {competitor_websites} to identify content approaches, 
    messaging themes, content frequency, engagement patterns, and content gaps. 
    Evaluate competitors' content strategy effectiveness across the same {project_types} 
    that {company_name} utilizes. Compare competitors' treatment of {content_topic} areas 
    and identify strategic opportunities based on competitor weaknesses or underserved topics.
  expected_output: >
    Comprehensive competitor analysis report detailing content strategies, strengths, 
    weaknesses, and unique approaches for each site in {competitor_websites}. Include 
    content gap analysis highlighting untapped opportunities within {content_topic} areas. 
    Provide competitive positioning recommendations that differentiate {company_name} from 
    competitor approaches while addressing audience needs. List specific content themes 
    and formats to explore based on competitive landscape analysis with priority rankings.
  agent: content_strategy_research_agent

content_calendar_creation_task:
  description: >
    Develop a dynamic content calendar based on strategy recommendations, competitor insights, 
    and {scheduling_preferences}. Balance content {project_types}, {content_topic} themes, 
    and distribution channels to maintain consistent audience engagement according to 
    {scheduling_preferences} while advancing strategic objectives. Incorporate flexibility 
    for responding to emerging trends and {performance_metrics} feedback.
  expected_output: >
    Detailed content calendar with scheduled content pieces, {content_topic} assignments, 
    {project_types} formats, distribution channels based on {scheduling_preferences}, and 
    target audience segments. Include theme progressions, campaign structures, and content 
    series relationships. Provide rationale for calendar structure and content sequencing 
    based on historical {performance_metrics}. Include mechanisms for calendar adjustments 
    based on ongoing performance data and market changes.
  agent: content_strategy_research_agent

ai_content_generation_task:
  description: >
    Generate multiple draft variations of content aligned with {brand_guidelines} for 
    specific {project_types} and {content_topic} using the OpenAI API. Create content that 
    adheres to brand voice, messaging priorities, and strategic objectives while delivering 
    value to target audiences. Ensure all generated content addresses specified {content_topic} 
    areas while meeting quality standards and accurately representing {company_name}'s 
    positioning.
  expected_output: >
    Multiple distinct content drafts for each requested content piece across different 
    {project_types}, each adhering to {brand_guidelines} while taking different creative 
    approaches to the assigned {content_topic}. Content variations should include alternative 
    headlines, structural approaches, tone variations, and call-to-action formulations. 
    Include explanations of how each variation aligns with {brand_guidelines} and strategic 
    objectives for the {content_topic}.
  agent: content_creation_testing_agent

content_testing_task:
  description: >
    Implement A/B testing frameworks to evaluate different content variations against 
    {performance_metrics} including engagement, reach, SEO impact, and conversion data. 
    Design testing methodologies appropriate for each {project_types}, establish success 
    criteria based on relevant {performance_metrics}, and analyze testing results to 
    identify top-performing content options. Refine content based on testing insights 
    and audience feedback patterns.
  expected_output: >
    Complete A/B testing plan with test variations for each {project_types}, metrics to be 
    measured from {performance_metrics}, audience sampling approach, and statistical 
    significance parameters. Testing results report with performance data for each variation, 
    statistical analysis, and clear recommendations for content refinement. Include insights 
    about which content elements most significantly impacted {performance_metrics} for each 
    {content_topic} and {project_types} combination.
  agent: content_creation_testing_agent

content_publishing_task:
  description: >
    Organize, schedule, and publish approved content across social media channels using 
    {social_accounts_credentials} and CMS platforms using {CMS_credentials} according to 
    {scheduling_preferences}. Ensure proper formatting for each platform, appropriate tagging 
    and categorization, and optimal publishing timing based on {scheduling_preferences}. 
    Maintain accurate records of all published content with platform-specific URLs and 
    identifiers for each {project_types}.
  expected_output: >
    Publishing confirmation report detailing successful content distribution across all 
    channels including platform-specific content URLs, publishing timestamps aligned with 
    {scheduling_preferences}, and formatting verification for each {project_types}. Content 
    inventory update with publishing status, location tracking, and scheduled promotion 
    activities. Alert notifications for any publishing issues requiring attention with 
    specific reference to affected {social_accounts_credentials} or {CMS_credentials}.
  agent: content_ad_management_agent

ad_campaign_management_task:
  description: >
    Launch and manage advertising campaigns on platforms configured with {ad_accounts_credentials} 
    based on approved content and campaign parameters. Configure audience targeting, bidding 
    strategies, budget allocations, and campaign schedules according to {scheduling_preferences}. 
    Monitor campaign {performance_metrics} in real-time and make data-driven adjustments to 
    maximize ROI and campaign effectiveness for each {content_topic} and {project_types}.
  expected_output: >
    Campaign launch confirmation with detailed campaign structure documentation including ad 
    groups, targeting parameters based on {content_topic} relevance, budget allocations, and 
    creative assets for each {project_types}. Performance monitoring dashboard with real-time 
    {performance_metrics} and historical performance trends. Adjustment recommendations based 
    on {performance_metrics} data with implementation confirmation and impact analysis for 
    each active campaign.
  agent: content_ad_management_agent

engagement_monitoring_task:
  description: >
    Continuously monitor real-time {performance_metrics} including engagement data (comments, 
    likes, shares) and other interaction metrics across all content distribution channels 
    configured with {social_accounts_credentials}, {CMS_credentials}, and {ad_accounts_credentials}. 
    Identify engagement patterns, audience response themes, and potential issues requiring 
    attention across different {project_types} and {content_topic} areas. Provide regular 
    engagement summary reports and real-time alerts for unusual engagement patterns.
  expected_output: >
    Real-time engagement monitoring dashboard with customizable {performance_metrics} display, 
    trend visualization, and comparative benchmarking across {project_types} and {content_topic} 
    categories. Engagement analysis reports identifying patterns, themes in audience comments, 
    and sentiment trends. Alert notifications for engagement thresholds or unusual patterns 
    requiring immediate attention. Engagement data integration with content performance database 
    for longitudinal analysis of {performance_metrics}.
  agent: content_ad_management_agent

predictive_analytics_task:
  description: >
    Apply advanced analytics to forecast future engagement trends, ad performance patterns, 
    and content effectiveness based on historical {performance_metrics} and current data. 
    Develop predictive models that anticipate audience behavior and campaign outcomes across 
    different {project_types} and {content_topic} areas. Generate automated recommendations 
    for strategy adjustments based on predictive insights and competitive positioning against 
    {competitor_websites}.
  expected_output: >
    Predictive performance forecast reports with expected {performance_metrics} projections, 
    conversion estimates, and ROI predictions for current campaigns across {project_types} and 
    {content_topic} categories. Trend analysis identifying emerging patterns in audience behavior 
    and content performance relative to {competitor_websites}. Automated recommendation engine 
    output with specific suggested adjustments to content strategy, ad campaigns using 
    {ad_accounts_credentials}, and distribution approaches based on predictive insights and 
    {scheduling_preferences}.
  agent: content_ad_management_agent