receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  memory_limiter:
    check_interval: 1s
    limit_mib: 500
    spike_limit_mib: 200
  resource:
    attributes:
      - key: service.name
        value: "ultimate-marketing-team"
        action: upsert
      - key: environment
        value: "${ENVIRONMENT}"
        action: upsert

exporters:
  prometheus:
    endpoint: 0.0.0.0:9464
    namespace: otel
  
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
  
  logging:
    loglevel: info
    sampling_initial: 5
    sampling_thereafter: 200

  elasticsearch:
    endpoints: ["http://elasticsearch:9200"]
    index: traces
    mapping:
      mode: infer

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource]
      exporters: [jaeger, elasticsearch, logging]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource]
      exporters: [prometheus, logging]