name: Search Console API Monitoring

on:
  schedule:
    # Run daily at 5:00 AM UTC
    - cron: '0 5 * * *'
  workflow_dispatch:
    inputs:
      notify:
        description: 'Send notifications if issues are detected'
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  monitor-search-console:
    name: Monitor Search Console API
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install requests
      
      - name: Run monitoring
        env:
          GOOGLE_OAUTH2_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH2_CLIENT_ID }}
          GOOGLE_OAUTH2_CLIENT_SECRET: ${{ secrets.GOOGLE_OAUTH2_CLIENT_SECRET }}
          TEST_GSC_REFRESH_TOKEN: ${{ secrets.TEST_GSC_REFRESH_TOKEN }}
          TEST_GSC_SITE_URL: ${{ secrets.TEST_GSC_SITE_URL }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          # Create logs directory
          mkdir -p logs
          
          # Run with notification if requested or if scheduled
          if [[ "${{ github.event_name }}" == "schedule" || "${{ github.event.inputs.notify }}" == "true" ]]; then
            python scripts/monitoring/monitor_search_console_api.py --notify
          else
            python scripts/monitoring/monitor_search_console_api.py
          fi
      
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: search-console-monitoring-logs
          path: |
            logs/search_console_monitoring.log
            logs/search_console_metrics/
          if-no-files-found: warn
      
      - name: Notify on job failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: "❌ Search Console Monitoring Job Failed"
          SLACK_MESSAGE: "The scheduled monitoring job for Google Search Console API failed. Please check the GitHub Actions logs."
          SLACK_COLOR: danger